# Generated by Django 3.2.6 on 2021-08-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(null=True, verbose_name='قیمت محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='insert_date',
            field=models.DateTimeField(verbose_name='ژمان ورود محصول به فروشگاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling',
            field=models.IntegerField(verbose_name='تعداد فروش انجام شده محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='special',
            field=models.BooleanField(verbose_name='محصول ویژه'),
        ),
    ]
