# Generated by Django 3.2.6 on 2021-08-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210822_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='mysite/shop/static/shop/images', verbose_name='تصویر محصول'),
        ),
    ]
