# Generated by Django 3.2.6 on 2021-08-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selling',
            field=models.IntegerField(null=True, verbose_name='تعداد فروش انجام شده محصول'),
        ),
    ]
